package main

var asciiDescription = map[int]string{
	0   : "Null character",
	1   : "Start of Heading",
	2   : "Start of Text",
	3   : "End of Text",
	4   : "End of Transmission",
	5   : "Enquiry",
	6   : "Acknowledge",
	7   : "Bell, Alert",
	8   : "Backspace",
	9   : "Horizontal Tab",
	10  : "Line Feed",
	11  : "Vertical Tabulation",
	12  : "Form Feed",
	13  : "Carriage Return",
	14  : "Shift Out",
	15  : "Shift In",
	16  : "Data Link Escape",
	17  : "Device Control One (XON)",
	18  : "Device Control Two",
	19  : "Device Control Three (XOFF)",
	20  : "Device Control Four",
	21  : "Negative Acknowledge",
	22  : "Synchronous Idle",
	23  : "End of Transmission Block",
	24  : "Cancel",
	25  : "End of medium",
	26  : "Substitute",
	27  : "Escape",
	28  : "File Separator",
	29  : "Group Separator",
	30  : "Record Separator",
	31  : "Unit Separator",
	32  : "Space",
	33  : "Exclamation mark",
	34  : "Double quotes (or speech marks)",
	35  : "Number sign",
	36  : "Dollar",
	37  : "Per cent sign",
	38  : "Ampersand",
	39  : "Single quote",
	40  : "Open parenthesis (or open bracket)",
	41  : "Close parenthesis (or close bracket)",
	42  : "Asterisk",
	43  : "Plus",
	44  : "Comma",
	45  : "Hyphen-minus",
	46  : "Period, dot or full stop",
	47  : "Slash or divide",
	48  : "Zero",
	49  : "One",
	50  : "Two",
	51  : "Three",
	52  : "Four",
	53  : "Five",
	54  : "Six",
	55  : "Seven",
	56  : "Eight",
	57  : "Nine",
	58  : "Colon",
	59  : "Semicolon",
	60  : "Less than (or open angled bracket)",
	61  : "Equals",
	62  : "Greater than (or close angled bracket)",
	63  : "Question mark",
	64  : "At sign",
	65  : "Uppercase A",
	66  : "Uppercase B",
	67  : "Uppercase C",
	68  : "Uppercase D",
	69  : "Uppercase E",
	70  : "Uppercase F",
	71  : "Uppercase G",
	72  : "Uppercase H",
	73  : "Uppercase I",
	74  : "Uppercase J",
	75  : "Uppercase K",
	76  : "Uppercase L",
	77  : "Uppercase M",
	78  : "Uppercase N",
	79  : "Uppercase O",
	80  : "Uppercase P",
	81  : "Uppercase Q",
	82  : "Uppercase R",
	83  : "Uppercase S",
	84  : "Uppercase T",
	85  : "Uppercase U",
	86  : "Uppercase V",
	87  : "Uppercase W",
	88  : "Uppercase X",
	89  : "Uppercase Y",
	90  : "Uppercase Z",
	91  : "Opening bracket",
	92  : "Backslash",
	93  : "Closing bracket",
	94  : "Caret - circumflex",
	95  : "Underscore",
	96  : "Grave accent",
	97  : "Lowercase a",
	98  : "Lowercase b",
	99  : "Lowercase c",
	100 : "Lowercase d",
	101 : "Lowercase e",
	102 : "Lowercase f",
	103 : "Lowercase g",
	104 : "Lowercase h",
	105 : "Lowercase i",
	106 : "Lowercase j",
	107 : "Lowercase k",
	108 : "Lowercase l",
	109 : "Lowercase m",
	110 : "Lowercase n",
	111 : "Lowercase o",
	112 : "Lowercase p",
	113 : "Lowercase q",
	114 : "Lowercase r",
	115 : "Lowercase s",
	116 : "Lowercase t",
	117 : "Lowercase u",
	118 : "Lowercase v",
	119 : "Lowercase w",
	120 : "Lowercase x",
	121 : "Lowercase y",
	122 : "Lowercase z",
	123 : "Opening brace",
	124 : "Vertical bar",
	125 : "Closing brace",
	126 : "Equivalency sign - tilde",
	127 : "Delete",
	128 : "Euro sign",
	129 : "Unused",
	130 : "Single low-9 quotation mark",
	131 : "Latin small letter f with hook",
	132 : "Double low-9 quotation mark",
	133 : "Horizontal ellipsis",
	134 : "Dagger",
	135 : "Double dagger",
	136 : "Modifier letter circumflex accent",
	137 : "Per mille sign",
	138 : "Latin capital letter S with caron",
	139 : "Single left-pointing angle quotation",
	140 : "Latin capital ligature OE",
	141 : "Unused",
	142 : "Latin capital letter Z with caron",
	143 : "Unused",
	144 : "Unused",
	145 : "Left single quotation mark",
	146 : "Right single quotation mark",
	147 : "Left double quotation mark",
	148 : "Right double quotation mark",
	149 : "Bullet",
	150 : "En dash",
	151 : "Em dash",
	152 : "Small tilde",
	153 : "Trade mark sign",
	154 : "Latin small letter S with caron",
	155 : "Single right-pointing angle quotation mark",
	156 : "Latin small ligature oe",
	157 : "Unused",
	158 : "Latin small letter z with caron",
	159 : "Latin capital letter Y with diaeresis",
	160 : "Non-breaking space",
	161 : "Inverted exclamation mark",
	162 : "Cent sign",
	163 : "Pound sign",
	164 : "Currency sign",
	165 : "Yen sign",
	166 : "Pipe, broken vertical bar",
	167 : "Section sign",
	168 : "Spacing diaeresis - umlaut",
	169 : "Copyright sign",
	170 : "Feminine ordinal indicator",
	171 : "Left double angle quotes",
	172 : "Negation",
	173 : "Soft hyphen",
	174 : "Registered trade mark sign",
	175 : "Spacing macron - overline",
	176 : "Degree sign",
	177 : "Plus-or-minus sign",
	178 : "Superscript two - squared",
	179 : "Superscript three - cubed",
	180 : "Acute accent - spacing acute",
	181 : "Micro sign",
	182 : "Pilcrow sign - paragraph sign",
	183 : "Middle dot - Georgian comma",
	184 : "Spacing cedilla",
	185 : "Superscript one",
	186 : "Masculine ordinal indicator",
	187 : "Right double angle quotes",
	188 : "Fraction one quarter",
	189 : "Fraction one half",
	190 : "Fraction three quarters",
	191 : "Inverted question mark",
	192 : "Latin capital letter A with grave",
	193 : "Latin capital letter A with acute",
	194 : "Latin capital letter A with circumflex",
	195 : "Latin capital letter A with tilde",
	196 : "Latin capital letter A with diaeresis",
	197 : "Latin capital letter A with ring above",
	198 : "Latin capital letter AE",
	199 : "Latin capital letter C with cedilla",
	200 : "Latin capital letter E with grave",
	201 : "Latin capital letter E with acute",
	202 : "Latin capital letter E with circumflex",
	203 : "Latin capital letter E with diaeresis",
	204 : "Latin capital letter I with grave",
	205 : "Latin capital letter I with acute",
	206 : "Latin capital letter I with circumflex",
	207 : "Latin capital letter I with diaeresis",
	208 : "Latin capital letter ETH",
	209 : "Latin capital letter N with tilde",
	210 : "Latin capital letter O with grave",
	211 : "Latin capital letter O with acute",
	212 : "Latin capital letter O with circumflex",
	213 : "Latin capital letter O with tilde",
	214 : "Latin capital letter O with diaeresis",
	215 : "Multiplication sign",
	216 : "Latin capital letter O with slash",
	217 : "Latin capital letter U with grave",
	218 : "Latin capital letter U with acute",
	219 : "Latin capital letter U with circumflex",
	220 : "Latin capital letter U with diaeresis",
	221 : "Latin capital letter Y with acute",
	222 : "Latin capital letter THORN",
	223 : "Latin small letter sharp s - ess-zed",
	224 : "Latin small letter a with grave",
	225 : "Latin small letter a with acute",
	226 : "Latin small letter a with circumflex",
	227 : "Latin small letter a with tilde",
	228 : "Latin small letter a with diaeresis",
	229 : "Latin small letter a with ring above",
	230 : "Latin small letter ae",
	231 : "Latin small letter c with cedilla",
	232 : "Latin small letter e with grave",
	233 : "Latin small letter e with acute",
	234 : "Latin small letter e with circumflex",
	235 : "Latin small letter e with diaeresis",
	236 : "Latin small letter i with grave",
	237 : "Latin small letter i with acute",
	238 : "Latin small letter i with circumflex",
	239 : "Latin small letter i with diaeresis",
	240 : "Latin small letter eth",
	241 : "Latin small letter n with tilde",
	242 : "Latin small letter o with grave",
	243 : "Latin small letter o with acute",
	244 : "Latin small letter o with circumflex",
	245 : "Latin small letter o with tilde",
	246 : "Latin small letter o with diaeresis",
	247 : "Division sign",
	248 : "Latin small letter o with slash",
	249 : "Latin small letter u with grave",
	250 : "Latin small letter u with acute",
	251 : "Latin small letter u with circumflex",
	252 : "Latin small letter u with diaeresis",
	253 : "Latin small letter y with acute",
	254 : "Latin small letter thorn",
	255 : "Latin small letter y with diaeresis",
}

